version: 1.0.{build}
image: Visual Studio 2017
install:
- ps: Install-Product node 8
- cmd: >-
    cd ./src/frontend



    
    npm install
build_script:
- cmd: >-
    cd %appveyor_build_folder%



    
    dotnet publish ./src/api/api.csproj



    
    cd ./src/frontend




    npm link @angular/cli



    
    ng build --prod
artifacts:
- path: src\api\bin\Debug\netcoreapp2.2\publish
  name: pitch-api

- path: src\frontend\dist\pitch-frontend
  name: pitch-frontend
deploy:
- provider: AzureAppServiceZipDeploy
  website: pitch-api
  username: $pitch-api
  password:
    secure: 2uXuJQsAT9cZJnkHBYanAZYVcoj5f13WR5Z9RTCfAyLMCtrFza16wEU8XZxog8H45aBPT6D3StgrnwnZqaUkGw==
  artifact: src\api\bin\Debug\netcoreapp2.2\pitch-api.zip
- provider: AzureWebJob
  website: pitch-frontend
  username: $pitch-frontend
  password:
    secure: FCl62SNhSp0ZYPFUdYNnspnbl5fZwgCHxOIOiif4vqE21E91okfuY2MDaIk1d4mXof8OpZ8Pm74AHfqKGG3WDw==
  artifact: pitch-frontend