version: 1.0.{build}
image: Visual Studio 2017
install:
- ps: Install-Product node 6
- cmd: >-
    cd ./src/frontend



    
    npm install
build_script:
- cmd: >-
cd %appveyor_build_folder%
   cd %appveyor_build_folder%



    
    
   dotnet publish ./src/api/api.csproj



    
    cd ./src/frontend



    
    ng build --prod
artifacts:
- path: src\api\bin\Debug\netcoreapp2.2\publish
  name: pitch-api

- path: src\frontend\dist\pitch-frontend
  name: pitch-frontend
deploy:
- provider: AzureAppServiceZipDeploy
  website: pitch-api
  username: $pitch-api
  password:
    secure: 9UfALmBvkt2ikqf1/Ga3OrLKS3/idP05YhOyWQk+u8JromsJH7D/vXCCZ4AvOGNAGTxvsWUilp1CiYyCXuVKWQ==
  artifact: src\api\bin\Debug\netcoreapp2.2\pitch-api.zip